--- #YAML:1.0
name:               Tkx-WinIco
version:            0.01
abstract:           The taskbar extension for Tkx on Win.
author:
    - Alexander Nusov <alexander.nusov+cpan@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
    Tkx:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
